export const HOME = '/'
export const SET_DESTINATARY = '/set-destinatary'
export const AUTH = '/auth'
export const DISPLAY_MESSAGE = '/message/:id'
export const THANK_YOU = '/thank-you'
export const SEND_MESSAGE = '/send-message'
